2024-04-18T20:44:13 {"cpu": 0.2939453125, "cpu_total": 2, "cpu_usage": 0.14697265625, "memory": 4055.0, "memory_total": 8883.0, "memory_usage": 0.45648992457503096, "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Pipeline playful_grimoire for run 2 in schedule 3 is alive.", "timestamp": 1713473053.623291, "uuid": "64fa79eccbe64c4da29946dc52bc82b7"}
2024-04-18T20:44:13 {"block_run_id": 11, "block_uuid": "metmuseumobjects", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 11: pipeline playful_grimoire block metmuseumobjects", "timestamp": 1713473053.80732, "uuid": "94b7db37151d4aa1adf60d4dcce5a7b8"}
2024-04-18T20:44:13 {"cpu": 0.2939453125, "cpu_total": 2, "cpu_usage": 0.14697265625, "memory": 4055.0, "memory_total": 8883.0, "memory_usage": 0.45648992457503096, "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Pipeline playful_grimoire for run 2 in schedule 3 is alive.", "timestamp": 1713473053.819233, "uuid": "533a1a24dc9c4f0e844062e8e6be1183"}
2024-04-18T20:44:14 {"block_run_id": 12, "block_uuid": "met_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 12: pipeline playful_grimoire block met_directors", "timestamp": 1713473054.039527, "uuid": "4329e7d2072d4dd3917c3f192edf1da7"}
2024-04-18T20:44:17 {"block_run_id": 12, "block_uuid": "met_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "BlockRun 12 (block_uuid: met_directors) completes.", "timestamp": 1713473057.621591, "uuid": "d37f2a365f2e43589cc3686e4ef712f7"}
2024-04-18T20:44:24 {"cpu": 0.3125, "cpu_total": 2, "cpu_usage": 0.15625, "memory": 4708.0, "memory_total": 8883.0, "memory_usage": 0.5300011257458066, "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Pipeline playful_grimoire for run 2 in schedule 3 is alive.", "timestamp": 1713473064.129355, "uuid": "5604708b0f37414191e24a4b45931ce7"}
2024-04-18T20:44:25 {"block_run_id": 14, "block_uuid": "prep_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 14: pipeline playful_grimoire block prep_directors", "timestamp": 1713473065.128402, "uuid": "1cb2ac5a670642b5b439e731e118db74"}
2024-04-18T20:44:27 {"block_run_id": 14, "block_uuid": "prep_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "BlockRun 14 (block_uuid: prep_directors) completes.", "timestamp": 1713473067.582604, "uuid": "a7f0a97632714a7992c2ea1f425e76dc"}
2024-04-18T20:44:33 {"cpu": 0.32568359375, "cpu_total": 2, "cpu_usage": 0.162841796875, "memory": 4640.0, "memory_total": 8883.0, "memory_usage": 0.5223460542609478, "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Pipeline playful_grimoire for run 2 in schedule 3 is alive.", "timestamp": 1713473073.729901, "uuid": "e8deab28b12f488d8cc2ce244c90fb47"}
2024-04-18T20:44:34 {"block_run_id": 18, "block_uuid": "directors_table", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 18: pipeline playful_grimoire block directors_table", "timestamp": 1713473074.260925, "uuid": "462e1ab59a584a2d89b033fc5cb39698"}
2024-04-18T20:44:34 {"block_run_id": 16, "block_uuid": "gcs_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 16: pipeline playful_grimoire block gcs_directors", "timestamp": 1713473074.304342, "uuid": "efce1fcfee5e4d6787207ad18d9d4926"}
2024-04-18T20:44:37 {"block_run_id": 16, "block_uuid": "gcs_directors", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "BlockRun 16 (block_uuid: gcs_directors) completes.", "timestamp": 1713473077.068662, "uuid": "407a02381c2849d398cc107d10630fbf"}
2024-04-18T20:44:38 {"block_run_id": 18, "block_uuid": "directors_table", "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "EXCEPTION", "message": "BlockRun 18 (block_uuid: directors_table) failed.", "timestamp": 1713473078.604844, "uuid": "1648cfab2f6b4b7eb86fef068cf0f10b", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1315, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1224, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1530, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 158, in _execute_block\n    outputs = execute_r_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 57, in execute_r_code\n    __execute_r_code(file_path)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 139, in __execute_r_code\n    subprocess.run(\n  File \"/usr/local/lib/python3.10/subprocess.py\", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['Rscript', '--vanilla', '/tmp/53a2443c-1851-4f49-be05-0df52269cad2.r']' returned non-zero exit status 1.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1610, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 315, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 591, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1135, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 422, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["Command '['Rscript', '--vanilla', '/tmp/53a2443c-1851-4f49-be05-0df52269cad2.r']' returned non-zero exit status 1."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1315, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1224, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1530, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 158, in _execute_block
    outputs = execute_r_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 57, in execute_r_code
    __execute_r_code(file_path)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 139, in __execute_r_code
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '--vanilla', '/tmp/53a2443c-1851-4f49-be05-0df52269cad2.r']' returned non-zero exit status 1.
2024-04-18T20:44:44 {"cpu": 0.33349609375, "cpu_total": 2, "cpu_usage": 0.166748046875, "memory": 4649.0, "memory_total": 8883.0, "memory_usage": 0.5233592254868851, "pipeline_run_id": 2, "pipeline_schedule_id": 3, "pipeline_uuid": "playful_grimoire", "hostname": "7902c592f721", "level": "INFO", "message": "Pipeline playful_grimoire for run 2 in schedule 3 is alive.", "timestamp": 1713473084.197954, "uuid": "61d9b78391c94bbb99246deff84b7637"}
